### ISSUE TITLE
 state mismatch, expected undefined, got: 

### ISSUE THREAD

**Issue by barbirict** [aborn/nuxt-openid-connect#28]
> 500 state mismatch, expected undefined, got:  at  (./src/runtime/server/routes/oidc/callback.ts:47:1) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Object.handler (./node_modules/h3/dist/index.mjs:1697:19) at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1907:7)

I can't get the playground to work, it only works if I manually change the openid-client dependency code and disable state checking. Config is the same as in the example with only the issuer url, clientid and secret changed. Any ideas?

**Comment by johnatas-x** [comment]
Hey @barbirict,

Did you find a trick to stop getting this error?
I also have it on my side

Thanks,

**Comment by barbirict** [comment]
> Hey @barbirict,
> 
> Did you find a trick to stop getting this error? I also have it on my side
> 
> Thanks,

Hi @johnatas-x,
sadly, I never did. Posted here in hope developers give me an answer, I put the project I was working on on pause in the meantime.

**Comment by johnatas-x** [comment]
Hi @barbirict,
Thanks for your answer.
For my part, I will switch to `nuxt-oidc-auth`
